### ISSUE TITLE
Can't see html for components

### ISSUE THREAD

**Issue by Greggless** [canonical-web-and-design/vanillaframework.io#185]
## Summary

I can't see the HTML for components. Which makes me sad.

## specs
💻 MacOS 10.14.1
🌐 Chrome 71.0.3578.75 (Official Build) beta (64-bit)

## Screenshot
![image](https://user-images.githubusercontent.com/23459065/49382825-4fc9de80-f70f-11e8-90f1-cf89317d9c9a.png)

**Comment by kwm14** [comment]
@Greggless this is common with a majority of pages serve, it normally takes a minute or 2 for the iframe to pull down the JS on the page.

Working for me but if you can check again that would be great 👍

**Comment by Greggless** [comment]
# ¯\\_(ツ)_/¯
My JS is enabled in Chrome, but it never loads the iframe

# 😭

**Comment by Greggless** [comment]
Whilst on https://docs.vanillaframework.io/en/patterns/pull-quote I get: 
![image](https://user-images.githubusercontent.com/23459065/50828669-ece4ec00-1339-11e9-8340-bf2e94b94e31.png)

**Comment by deadlight** [comment]
The examples are served in an entirely different way now, this issue should no longer be valid
