### ISSUE TITLE
Add news feed

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanillaframework.io#208]
Would be nice to add a client based news feed to the site. We could fetch articles from the blog filtered by the vanilla tag.

**Comment by kwm14** [comment]
@anthonydillon how funny, literally opened an issue about this before you did [here](https://github.com/ubuntudesign/design-vanillaframework.io/issues/14)

**Comment by deadlight** [comment]
Closing duplicate issue.
