### ISSUE TITLE
Link to VF React Storybook 404s

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanillaframework.io#215]
Link to VF React Storybook on homepage 404s

<img width="1157" alt="Screenshot 2019-06-03 at 22 37 11" src="https://user-images.githubusercontent.com/505570/58836269-42ef5e80-8650-11e9-8cb2-e9978b56e6f3.png">

**Comment by kwm14** [comment]
Cheers @barrymcgee we will fix this when upgrading vf.io to beta.1 ahead of the release 👍

**Comment by kwm14** [comment]
Actually, from further investigation, this repo and project has been archived, so when we update the site to beta I will make sure we remove 'Vanilla react' section 😄

**Comment by kwm14** [comment]
@nottrobin found the broken link. So we can fix up [here](https://github.com/canonical-web-and-design/vanillaframework.io/issues/217#issuecomment-499098029) 👍
