### ISSUE TITLE
The "who's using vanilla" logos on the homepage should be links

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanillaframework.io#216]
I'd have thought the logos under "who's using vanilla" should probably be links to the sites where vanilla is used. This would make sense to me.

![image](https://user-images.githubusercontent.com/519935/58961431-fd8e7680-87a0-11e9-9a8c-d4bba84daf0e.png)

**Comment by kwm14** [comment]
Good shout @nottrobin 👍 will add to small tasks as we're upgrading the site 😄

**Comment by kwm14** [comment]
@deadlight can we update these links too, please 😃 

- Ubuntu - https://www.ubuntu.com/
- MAAS - https://maas.io/
- Juju - https://jaas.ai/
- Snapcraft - https://snapcraft.io/
- LXD - https://linuxcontainers.org/
- conjure-up - https://conjure-up.io/

**Comment by nottrobin** [comment]
To stretch this work even further - it might also be nice to link to `/showcase` from this section.
