### ISSUE TITLE
Update the list of contributors on the /contribute page

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanillaframework.io#219]
## Summary

We should update the list of contributors on the site to, at least, include @lyubomir-popov

**Comment by kwm14** [comment]
## Design update
Updated design to include @lyubomir-popov to the team 👍 

### 001
Update to `3-col` and keep same styling (sorry for my long name #wrapping)

![vf io-community-009](https://user-images.githubusercontent.com/17748020/59366328-16af9e00-8d32-11e9-908f-56593f147ab7.png)

### 002
As we link to our GitHub pages thought it made sense to use our GitHub name and avatar so when linked it's consistent.

![vf io-community-010](https://user-images.githubusercontent.com/17748020/59366329-16af9e00-8d32-11e9-9b6c-9c42a630b5e6.png)

**Comment by lyubomir-popov** [comment]
@kwm14 please use my github avatar :)
