### ISSUE TITLE
Paragraph should be list in browser support

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanillaframework.io#220]
## Summary

I have the feeling the paragraph of text under "How bugs are prioritised" in https://vanillaframework.io/browser-support is supposed to be a list.

## Current and expected result

Like so:

- If the bug prevents access to core content (for example, by hiding it or covering it), it should be prioritised 
- If the bug relates to visual differences that do not affect access to content on modern browsers, it should be queued up
- Priority level should be determined case by case 
- If the bug relates to visual differences that do not affect access to content on old browsers, it should be deprioritised, and potentially marked as “Won’t fix” (this should be decided case by case).

**Comment by kwm14** [comment]
Good catch. Thanks @yaili 👍
