### ISSUE TITLE
Remove references to gulp

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanillaframework.io#225]
**Describe the bug**
The [contribute page](https://vanillaframework.io/contribute) contains references to gulp, which is no longer used in the framework

**To Reproduce**
1. Go to https://vanillaframework.io/contribute
2. Search for "gulp"

**Expected behavior**
An up-to-date set of instructions for testing

**Comment by kwm14** [comment]
@deadlight what are the updated set of instructions for testing?

I've got a [PR](https://github.com/canonical-web-and-design/vanillaframework.io/pull/226) in for updating the team on the contribute page, so I can add this into that PR if you like? 👍

**Comment by anthonydillon** [comment]
@kwm14 the new way to test the code base is `./run test` instead of `gulp test`
