### ISSUE TITLE
[suggestion] Having upload date for sketch file

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanillaframework.io#238]
Not sure if it's really necessary or how many times you actually update it, but I was thinking it could be nice if we tell people when the sketch file was updated/uploaded? Maybe just a date or something.

**Comment by anasereijo** [comment]
I know it should be by vanilla version but I know sometimes you fix or update things on sketch so could be useful

**Comment by kwm14** [comment]
In line with this addition, I will be creating a new layout for the Downloads section, as this section of the site is popular with users 😄

**Comment by kwm14** [comment]
## Downloads
Current downloads section.

<img width="719" alt="Screenshot 2019-10-02 at 17 16 55" src="https://user-images.githubusercontent.com/17748020/66062020-82fc1a80-e538-11e9-9514-4cf9b81ce8d9.png">

**Comment by kwm14** [comment]
## Initial exploration
- Added upload date to Sketch file and Framework
- New layout for the downloads section
- Add subscribe content

### 001
![downloads-001](https://user-images.githubusercontent.com/17748020/66062106-b3dc4f80-e538-11e9-881d-0d0f7f59a627.png)

### 002
![downloads-002](https://user-images.githubusercontent.com/17748020/66062107-b3dc4f80-e538-11e9-8a1d-b32ba3729c0b.png)

### 003
![downloads-003](https://user-images.githubusercontent.com/17748020/66062108-b474e600-e538-11e9-89fb-bb2504ca3a11.png)

@anasereijo @spencerbygraves ready for design review 👀 😉

**Comment by kwm14** [comment]
## Design review
Meetings notes can be found [here](https://github.com/canonical-web-and-design/meeting-notes/issues/449#issue-501994872).

**Comment by kwm14** [comment]
## Updated exploration
- Design updates based on _Design review_ weekly earlier today 
- @anasereijo @spencerbygraves ready for design review 👀 

### 005
![downloads-005](https://user-images.githubusercontent.com/17748020/66129589-1dfffd80-e5e8-11e9-8121-883bde010fe9.png)

**Comment by anasereijo** [comment]
Looks good to me 👍 just make sure you type _Receive_ instead of _Recieve_ 😝

**Comment by kwm14** [comment]
> Looks good to me 👍 just make sure you type _Receive_ instead of _Recieve_ 😝

Good spot 😉

**Comment by spencerbygraves** [comment]
@kwm14 I think "Subscribe" is better than "Join", as you're not asking someone to become a member. And you have "Subscribe" in the button.

I'd also say "Receive the Vanilla newsletter to learn more about..."

Other than that, looks good 👍

**Comment by kwm14** [comment]
Thanks @spencerbygraves @anasereijo design updated accordingly 👍 

### 006
![downloads-006](https://user-images.githubusercontent.com/17748020/66137101-7e953780-e5f4-11e9-9c5f-303979720ee7.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Design added to the homepage redesign [issue](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/15). 💯
