### ISSUE TITLE
Link to  the coding standards page is broken

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/vanillaframework.io#253]
https://vanillaframework.io/coding-standards

**Comment by kwm14** [comment]
@spencerbygraves good spot. This page has recently been removed from the site, but we should redirect this URL to https://vanillaframework.io/contribute

**Comment by kwm14** [comment]
As this page has been removed from the codebase and repo it's no longer hosted so we can't redirect users who visit this page. @spencerbygraves if you clear your browser's cache you will notice the new navigation structure. 

<img width="691" alt="Screenshot 2019-10-21 at 10 42 32" src="https://user-images.githubusercontent.com/17748020/67194687-8247fd00-f3ef-11e9-9131-1cca1609b1c4.png">
