### ISSUE TITLE
Typo in Site Header

### ISSUE THREAD

**Issue by robireton** [canonical-web-and-design/vanillaframework.io#275]
## Summary

The header text reads, “Backed by open-source code and written *is* Sass by the Canonical Web Team.” That ‘is’ should be ‘in’.

## Process

view https://vanillaframework.io/

## Current and expected result

typo in header

## Screenshot

<img width="1045" alt="Screen Shot 2020-01-14 at 3 27 17 PM" src="https://user-images.githubusercontent.com/10468698/72380056-9cd5fd80-36e2-11ea-9acb-526d17e299f6.png">

**Comment by bartaz** [comment]
@robireton Good spot, thanks! It seems it's already fixed by #273 but we haven't deployed it yet.
