### ISSUE TITLE
Link to Sketch file not working

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/vanillaframework.io#276]
The link to the Sketch library on the home page gives a 404 error. 

**To Reproduce**
1. Go to https://vanillaframework.io/
2. Click on 'Download the Sketch UI kit'
3. See error

**Expected behavior**
File starts downloading.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.2
 - Browser: Chrome
 - Version: 79.0.3945.117

**Comment by bartaz** [comment]
Seems like jenkins job that was used to update the redirect doesn't work anymore (even though it claims the build 'succeeds').

**Comment by bartaz** [comment]
Fixed on jenkins
