### ISSUE TITLE
Cache busting to static assets needed for static assets

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanillaframework.io#96]
## Problem

When we release new versions of the site, particularly after bumping to new versions of Vanilla Framework, styling bugs can appear and make the site appear broken as we are not cache busting the CSS and JS.

## Solution

Add caching busting into build to affix the latest commit hex onto the end of static asset includes;

e.g. `...main.css?h=d6d0fcf4 `

**Comment by bartaz** [comment]
We moved site to Flask, no static page anymoew
